enum MessageType {
	Default,
	Recipient_Add,
	Recipient_Remove,
	Call,
	Channel_Name_Change,
	Channel_Icon_Change,
	Channel_Pinned_Message,
	Guild_Member_Join,
	User_Premium_Guild_Subscription,
	User_Premium_Guild_Subscription_Tier_1,
	User_Premium_Guild_Subscription_Tier_2,
	User_Premium_Guild_Subscription_Tier_3,
	Channel_Follow_Add = 12,
	Guild_Discovery_Disqualified = 14,
	Guild_Discovery_Requalified,
	Guild_Discovery_Grace_Period_Initial_Warning,
	Guild_Discovery_Grace_Period_Final_Warning,
	Thread_Created,
	Reply,
	Chat_Input_Command,
	Thread_Starter_Message,
	Guild_Invite_Reminder,
	Context_Menu_Command,
}